spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://nanal-db-test.ci9gijozh24o.ap-northeast-2.rds.amazonaws.com:3306/NanalDB?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: nanal
    password: nanal_test12

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    database: mysql
    # Initial Data config
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:/sql/*
      mode: always
      separator: ^;

  # thymeleaf Config
  thymeleaf:
    prefix: classpath:/static/

# Redis Config
redis:
  host: redis
  port: 6379

# Jwt Config
jwt:
  token:
    secret: retrospecter
    # 3분 // 현재 한달!!!
    access-period: 2592000000
    # 10분
    refresh-period: 600000
    # 5분
    reissue-period: 300000
    refresh-token-storage-period: 600000

# App id
app-id:
  kakao: 855507
  google: 303870319503

# Slack
slack:
  token: xoxb-4198603287202-4794874907156-InjSGyicOXvpUP9N5qcNJqjp
  channel:
    monitor: C04PE21NF7F

# Email
mail:
  smtp:
    auth: true
    port: 465
    timeout: 500
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465

# admin 구글 계정
AdminMail:
  id: login2.onlog@gmail.com
  password: intgpnjdonpzuxru