spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://nanal-db-test.ci9gijozh24o.ap-northeast-2.rds.amazonaws.com:3306/NanalDB?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: nanal
    password: nanal1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    database: mysql
    # Initial Data config
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:/sql/*
      mode: always
      separator: ^;

  # oauth Config
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 303870319503-91k7h7mq92nla8mpmbfuqsrk542hc6cf.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          kakao:
            client-id: 24f37763646acd5ddd1d2b6f00aed2ac
            client-secret: pOEsyGjTLt3knYbEqXrTMj9NV6wlJ0Y4
            redirect-uri: http://ec2-3-35-144-253.ap-northeast-2.compute.amazonaws.com/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            client-authentication-method: POST
            scope:
              - profile_nickname
              - account_email
              - gender
              - age_range

          naver:
            client-id: 1XVrozNS5LrSXiKRruRa
            client-secret: 1dWDETIJn1
            redirect-uri: http://ec2-3-35-144-253.ap-northeast-2.compute.amazonaws.com/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - nickname
              - email
              - gender
              - age

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  # thymeleaf Config
  thymeleaf:
    prefix: classpath:/static/

# Redis Config
redis:
  host: redis
  port: 6379

# Jwt Config
jwt:
  token:
    secret: retrospecter
    # 3분 // 현재 한달!!!
    access-period: 2592000000
    # 10분
    refresh-period: 600000
    # 5분
    reissue-period: 300000
    refresh-token-storage-period: 600000